<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Employee392to401 extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'employee_no' => '392',
                'username' => 'Ma. Evalyn',
                'password' => password_hash('default', PASSWORD_BCRYPT),
                'firstname' => 'Ma. Evalyn',
                'middlename' => 'Makalintal',
                'lastname' => 'Paculba',
                'address' => 'Block 3 Lot 16 Grandview Heights Phase 2 Sambat Tanauan Batangas',
                'birthdate' => '1992-08-02',
                'contact_info' => '0991-493-4000',
                'gender' => 'Female',
                'datehired' => '2025-08-18',
                'profile_image' => 'thanossmile.jpg',
                'created_on' => '2025-08-20',
                'barcode' => '392',
                'email' => null,
                'separationdate' => '2025-03-10',
                'department_id' => 7,
                'organization_id' => 4,
            ],
            [
                'employee_no' => '393',
                'username' => 'Lyndon',
                'password' => '$2y$10$Kd2bQCobw75I2TiFK7cKAu2fsC2VB0gwAjeFuR.jbPGh1c1S5J1W.',
                'firstname' => 'Lyndon Allen',
                'middlename' => 'Mendiola',
                'lastname' => 'Sales',
                'address' => 'Calamba Hills Village Phase 2, Barandal, Calamca City Laguna',
                'birthdate' => '2003-03-19',
                'contact_info' => '0992-377-4683',
                'gender' => 'Male',
                'datehired' => '2024-08-18',
                'profile_image' => 'thanossmile.jpg',
                'created_on' => '2025-08-20',
                'barcode' => '393',
                'email' => null,
                'separationdate' => null,
                'department_id' => 11,
                'organization_id' => 1,
            ],
            [
                'employee_no' => '394',
                'username' => 'Gary',
                'password' => password_hash('default', PASSWORD_BCRYPT),
                'firstname' => 'Gary',
                'middlename' => 'Zapata',
                'lastname' => 'Gordo',
                'address' => '515 Brgy Sirang Lupa, Calamba City Laguna',
                'birthdate' => '1992-02-10',
                'contact_info' => '0991-827-4643',
                'gender' => 'Male',
                'datehired' => '2025-08-18',
                'profile_image' => 'thanossmile.jpg',
                'created_on' => '2025-08-20',
                'barcode' => '394',
                'email' => null,
                'separationdate' => '2025-11-04',
                'department_id' => 7,
                'organization_id' => 4,
            ],
            [
                'employee_no' => '395',
                'username' => 'glen.ona',
                'password' => '$2y$10$ZvHOE5WTXiad8H2j8YWcMeq9gMp.n11rU4wkwq3qM5fL4ZhCeB7te',
                'firstname' => 'GLEN',
                'middlename' => 'SAMIANO',
                'lastname' => 'OÑA',
                'address' => '106, BUROL, CALAMBA CITY',
                'birthdate' => '1986-01-04',
                'contact_info' => '09063526240',
                'gender' => 'Male',
                'datehired' => '2025-09-29',
                'profile_image' => 'Untitled design (4).png',
                'created_on' => '2025-09-29',
                'barcode' => '395',
                'email' => null,
                'separationdate' => null,
                'department_id' => 7,
                'organization_id' => 4,
            ],
            [
                'employee_no' => '396',
                'username' => 'dbalanon197170',
                'password' => '$2y$10$AF62mE80KXsqePdpKIb0R.xSn6PnT5uaNVuAs1cfpz7e.lN9hn1mq',
                'firstname' => 'Darmie',
                'middlename' => 'Flores',
                'lastname' => 'Balanon',
                'address' => 'Brg Buenavista Barandal Calamba Laguna',
                'birthdate' => '1971-04-13',
                'contact_info' => '09092576624',
                'gender' => 'Male',
                'datehired' => '2025-10-01',
                'profile_image' => 'Untitled design (7).png',
                'created_on' => '2025-10-01',
                'barcode' => '396',
                'email' => null,
                'separationdate' => null,
                'department_id' => 7,
                'organization_id' => 4,
            ],
            [
                'employee_no' => '397',
                'username' => 'Roseannjoy',
                'password' => '$2y$10$NLr3u7K.zgnUxR8HfwGWxO5Lj/QAQgoMFK9JC4j4vcCqvzjuWhCL2',
                'firstname' => 'Rose Ann Joy',
                'middlename' => 'Bitong',
                'lastname' => 'Abu',
                'address' => 'Luta Sur Malvar Batangas',
                'birthdate' => '1994-09-19',
                'contact_info' => '09970829078',
                'gender' => 'Female',
                'datehired' => '2025-03-11',
                'profile_image' => '589906669_1497261428054605_7919848906035580422_n-removebg-preview.png',
                'created_on' => '2025-11-03',
                'barcode' => '397',
                'email' => null,
                'separationdate' => null,
                'department_id' => 7,
                'organization_id' => 4,
            ],
            [
                'employee_no' => '398',
                'username' => 'Rinze',
                'password' => password_hash('default', PASSWORD_BCRYPT),
                'firstname' => 'Rinze John',
                'middlename' => 'Mendezabal',
                'lastname' => 'Escurel',
                'address' => 'P1 Blok 31 Lot 55 Mabuhay City Baclaran Cabuayo Laguna',
                'birthdate' => '1995-11-22',
                'contact_info' => '0985-7755-710',
                'gender' => 'Male',
                'datehired' => '2025-11-19',
                'profile_image' => 'Untitled design (11).png',
                'created_on' => '2025-11-21',
                'barcode' => '398',
                'email' => null,
                'separationdate' => null,
                'department_id' => 1,
                'organization_id' => 11,
            ],
            [
                'employee_no' => '399',
                'username' => 'Mathew',
                'password' => password_hash('default', PASSWORD_BCRYPT),
                'firstname' => 'Mathew',
                'middlename' => 'Labog',
                'lastname' => 'Delos Santos',
                'address' => 'South Ville 6 B2 L129 Brgy Kay-Anlog Calamba City Laguna',
                'birthdate' => '1997-12-20',
                'contact_info' => '0991-916-0927',
                'gender' => 'Male',
                'datehired' => '2025-11-19',
                'profile_image' => 'Untitled design (6).png',
                'created_on' => '2025-11-20',
                'barcode' => '399',
                'email' => 'matkee28@gmail.com',
                'separationdate' => null,
                'department_id' => 7,
                'organization_id' => 4,
            ],
            [
                'employee_no' => '400',
                'username' => 'm.latayan_',
                'password' => '$2y$10$zHm05x//.GHKuPLakkb0aeufFBQE3Sm9P.UORf1BNxIc6M33VS9we',
                'firstname' => 'Mark Lyndon',
                'middlename' => 'Dimaano',
                'lastname' => 'Latayan',
                'address' => 'Brgy. San Andres Malvar, Batangas',
                'birthdate' => '1999-07-30',
                'contact_info' => '09672967327',
                'gender' => 'Male',
                'datehired' => '2025-11-27',
                'profile_image' => 'Untitled design (10).png',
                'created_on' => '2025-11-28',
                'barcode' => '400',
                'email' => 'lyndonlatayan@gmail.com',
                'separationdate' => null,
                'department_id' => 7,
                'organization_id' => 4,
            ],
            [
                'employee_no' => '401',
                'username' => 'A.Domulot',
                'password' => '$2y$10$LxgVHR4n/BXfqgqpuwYOoOPdksE8R5zb.KBFiFPrwl5zk2ouXHcbe',
                'firstname' => 'Arnold',
                'middlename' => 'Viray',
                'lastname' => 'Domulot',
                'address' => 'Blk 1 Lot 5 classic 2 Brgy San vicente Santo tomas Batangas',
                'birthdate' => '1989-08-24',
                'contact_info' => '09630008001',
                'gender' => 'Male',
                'datehired' => '2025-11-27',
                'profile_image' => 'Untitled design (5).png',
                'created_on' => '2025-11-28',
                'barcode' => '401',
                'email' => 'domulot1026@gmail.com',
                'separationdate' => null,
                'department_id' => 7,
                'organization_id' => 4,
            ],
        ];

        foreach ($employees as $employeeData) {
            DB::table('users')->updateOrInsert(
                ['employee_no' => $employeeData['employee_no']],
                array_merge($employeeData, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
