/*
-- Query: SELECT *
FROM spears24.employees
WHERE employee_no BETWEEN 392 AND 401
LIMIT 0, 50000

-- Date: 2026-01-06 10:45
*/
INSERT INTO `` (`id`,`employee_no`,`username`,`password`,`firstname`,`middlename`,`lastname`,`address`,`birthdate`,`contact_info`,`gender`,`position_id`,`department_id`,`schedule_id`,`organization_id`,`datehired`,`photo`,`created_on`,`usernameadmin`,`passwordadmin`,`barcode`,`email`,`separationdate`,`userrole`,`useraccess`,`safetycouncil`,`vacationleave`,`sickleave`,`emergencyleave`,`earnVL`,`earnSL`,`earnEL`,`civil_status`,`emergency_contact`,`emergency_number`,`sss_number`,`philhealth_number`,`pagibig_number`,`tin_number`,`work_status`,`cedula_govid`,`rate`) VALUES (380,'392','Ma. Evalyn','','Ma. Evalyn','Makalintal','Paculba','Block 3 Lot 16 Grandview Heights Phase 2 Sambat Tanauan Batangas','1992-08-02','0991-493-4000','Female',35,7,1,4,'2025-08-18','thanossmile.jpg','2025-08-20','','','','no email','2025-03-10','',0,0,0,0,0,0,0,0,'','',0,0,0,0,0,'','',0.00);
INSERT INTO `` (`id`,`employee_no`,`username`,`password`,`firstname`,`middlename`,`lastname`,`address`,`birthdate`,`contact_info`,`gender`,`position_id`,`department_id`,`schedule_id`,`organization_id`,`datehired`,`photo`,`created_on`,`usernameadmin`,`passwordadmin`,`barcode`,`email`,`separationdate`,`userrole`,`useraccess`,`safetycouncil`,`vacationleave`,`sickleave`,`emergencyleave`,`earnVL`,`earnSL`,`earnEL`,`civil_status`,`emergency_contact`,`emergency_number`,`sss_number`,`philhealth_number`,`pagibig_number`,`tin_number`,`work_status`,`cedula_govid`,`rate`) VALUES (381,'393','Lyndon','$2y$10$Kd2bQCobw75I2TiFK7cKAu2fsC2VB0gwAjeFuR.jbPGh1c1S5J1W.','Lyndon Allen','Mendiola','Sales','Calamba Hills Village Phase 2, Barandal, Calamca City Laguna','2003-03-19','0992-377-4683','Male',92,11,2,1,'2024-08-18','thanossmile.jpg','2025-08-20','','','','no email','0000-00-00','0',0,0,0,0,0,0,0,0,'','',0,0,0,0,0,'','',0.00);
INSERT INTO `` (`id`,`employee_no`,`username`,`password`,`firstname`,`middlename`,`lastname`,`address`,`birthdate`,`contact_info`,`gender`,`position_id`,`department_id`,`schedule_id`,`organization_id`,`datehired`,`photo`,`created_on`,`usernameadmin`,`passwordadmin`,`barcode`,`email`,`separationdate`,`userrole`,`useraccess`,`safetycouncil`,`vacationleave`,`sickleave`,`emergencyleave`,`earnVL`,`earnSL`,`earnEL`,`civil_status`,`emergency_contact`,`emergency_number`,`sss_number`,`philhealth_number`,`pagibig_number`,`tin_number`,`work_status`,`cedula_govid`,`rate`) VALUES (382,'394','Gary','','Gary','Zapata','Gordo','515 Brgy Sirang Lupa, Calamba City Laguna','1992-02-10','0991-827-4643','Male',93,7,1,4,'2025-08-18','thanossmile.jpg','2025-08-20','','','','no email','2025-11-04','',0,0,0,0,0,0,0,0,'','',0,0,0,0,0,'','',0.00);
INSERT INTO `` (`id`,`employee_no`,`username`,`password`,`firstname`,`middlename`,`lastname`,`address`,`birthdate`,`contact_info`,`gender`,`position_id`,`department_id`,`schedule_id`,`organization_id`,`datehired`,`photo`,`created_on`,`usernameadmin`,`passwordadmin`,`barcode`,`email`,`separationdate`,`userrole`,`useraccess`,`safetycouncil`,`vacationleave`,`sickleave`,`emergencyleave`,`earnVL`,`earnSL`,`earnEL`,`civil_status`,`emergency_contact`,`emergency_number`,`sss_number`,`philhealth_number`,`pagibig_number`,`tin_number`,`work_status`,`cedula_govid`,`rate`) VALUES (383,'395','glen.ona','$2y$10$ZvHOE5WTXiad8H2j8YWcMeq9gMp.n11rU4wkwq3qM5fL4ZhCeB7te','GLEN','SAMIANO','OÑA','106, BUROL, CALAMBA CITY','1986-01-04','09063526240','Male',35,7,2,4,'2025-09-29','Untitled design (4).png','2025-09-29','','','','2','0000-00-00','0',0,0,0,0,0,0,0,0,'','',0,0,0,0,0,'','',0.00);
INSERT INTO `` (`id`,`employee_no`,`username`,`password`,`firstname`,`middlename`,`lastname`,`address`,`birthdate`,`contact_info`,`gender`,`position_id`,`department_id`,`schedule_id`,`organization_id`,`datehired`,`photo`,`created_on`,`usernameadmin`,`passwordadmin`,`barcode`,`email`,`separationdate`,`userrole`,`useraccess`,`safetycouncil`,`vacationleave`,`sickleave`,`emergencyleave`,`earnVL`,`earnSL`,`earnEL`,`civil_status`,`emergency_contact`,`emergency_number`,`sss_number`,`philhealth_number`,`pagibig_number`,`tin_number`,`work_status`,`cedula_govid`,`rate`) VALUES (384,'396','dbalanon197170','$2y$10$AF62mE80KXsqePdpKIb0R.xSn6PnT5uaNVuAs1cfpz7e.lN9hn1mq','Darmie','Flores','Balanon','Brg Buenavista Barandal Calamba Laguna\r\n','1971-04-13','09092576624','Male',8,7,2,4,'2025-10-01','Untitled design (7).png','2025-10-01','','','','no email','0000-00-00','0',0,0,0,0,0,0,0,0,'','',0,0,0,0,0,'','',0.00);
INSERT INTO `` (`id`,`employee_no`,`username`,`password`,`firstname`,`middlename`,`lastname`,`address`,`birthdate`,`contact_info`,`gender`,`position_id`,`department_id`,`schedule_id`,`organization_id`,`datehired`,`photo`,`created_on`,`usernameadmin`,`passwordadmin`,`barcode`,`email`,`separationdate`,`userrole`,`useraccess`,`safetycouncil`,`vacationleave`,`sickleave`,`emergencyleave`,`earnVL`,`earnSL`,`earnEL`,`civil_status`,`emergency_contact`,`emergency_number`,`sss_number`,`philhealth_number`,`pagibig_number`,`tin_number`,`work_status`,`cedula_govid`,`rate`) VALUES (385,'397','Roseannjoy','$2y$10$NLr3u7K.zgnUxR8HfwGWxO5Lj/QAQgoMFK9JC4j4vcCqvzjuWhCL2','Rose Ann Joy','Bitong','Abu','Luta Sur Malvar Batangas','1994-09-19','09970829078','Female',35,7,1,4,'2025-03-11','589906669_1497261428054605_7919848906035580422_n-removebg-preview.png','2025-11-03','','','','None','0000-00-00','0',0,0,0,0,0,0,0,0,'','',0,0,0,0,0,'','',0.00);
INSERT INTO `` (`id`,`employee_no`,`username`,`password`,`firstname`,`middlename`,`lastname`,`address`,`birthdate`,`contact_info`,`gender`,`position_id`,`department_id`,`schedule_id`,`organization_id`,`datehired`,`photo`,`created_on`,`usernameadmin`,`passwordadmin`,`barcode`,`email`,`separationdate`,`userrole`,`useraccess`,`safetycouncil`,`vacationleave`,`sickleave`,`emergencyleave`,`earnVL`,`earnSL`,`earnEL`,`civil_status`,`emergency_contact`,`emergency_number`,`sss_number`,`philhealth_number`,`pagibig_number`,`tin_number`,`work_status`,`cedula_govid`,`rate`) VALUES (386,'399','Mathew','','Mathew','Labog','Delos Santos','South Ville 6 B2 L129 Brgy Kay-Anlog Calamba City Laguna','1997-12-20','0991-916-0927','Male',35,7,1,4,'2025-11-19','Untitled design (6).png','2025-11-20','','','','matkee28@gmail.com','0000-00-00','0',0,0,0,0,0,0,0,0,'','',0,0,0,0,0,'','',0.00);
INSERT INTO `` (`id`,`employee_no`,`username`,`password`,`firstname`,`middlename`,`lastname`,`address`,`birthdate`,`contact_info`,`gender`,`position_id`,`department_id`,`schedule_id`,`organization_id`,`datehired`,`photo`,`created_on`,`usernameadmin`,`passwordadmin`,`barcode`,`email`,`separationdate`,`userrole`,`useraccess`,`safetycouncil`,`vacationleave`,`sickleave`,`emergencyleave`,`earnVL`,`earnSL`,`earnEL`,`civil_status`,`emergency_contact`,`emergency_number`,`sss_number`,`philhealth_number`,`pagibig_number`,`tin_number`,`work_status`,`cedula_govid`,`rate`) VALUES (387,'398','Rinze','','Rinze John','Mendezabal','Escurel','P1 Blok 31 Lot 55 Mabuhay City Baclaran Cabuayo Laguna','1995-11-22','0985-7755-710','Male',47,1,2,11,'2025-11-19','Untitled design (11).png','2025-11-21','','','','None','0000-00-00','0',0,0,0,0,0,0,0,0,'','',0,0,0,0,0,'','',0.00);
INSERT INTO `` (`id`,`employee_no`,`username`,`password`,`firstname`,`middlename`,`lastname`,`address`,`birthdate`,`contact_info`,`gender`,`position_id`,`department_id`,`schedule_id`,`organization_id`,`datehired`,`photo`,`created_on`,`usernameadmin`,`passwordadmin`,`barcode`,`email`,`separationdate`,`userrole`,`useraccess`,`safetycouncil`,`vacationleave`,`sickleave`,`emergencyleave`,`earnVL`,`earnSL`,`earnEL`,`civil_status`,`emergency_contact`,`emergency_number`,`sss_number`,`philhealth_number`,`pagibig_number`,`tin_number`,`work_status`,`cedula_govid`,`rate`) VALUES (388,'400','m.latayan_','$2y$10$zHm05x//.GHKuPLakkb0aeufFBQE3Sm9P.UORf1BNxIc6M33VS9we','Mark Lyndon','Dimaano','Latayan','Brgy. San Andres Malvar, Batangas','1999-07-30','09672967327','Male',46,7,2,4,'2025-11-27','Untitled design (10).png','2025-11-28','','','','lyndonlatayan@gmail.com','0000-00-00','0',0,0,0,0,0,0,0,0,'','',0,0,0,0,0,'','',0.00);
INSERT INTO `` (`id`,`employee_no`,`username`,`password`,`firstname`,`middlename`,`lastname`,`address`,`birthdate`,`contact_info`,`gender`,`position_id`,`department_id`,`schedule_id`,`organization_id`,`datehired`,`photo`,`created_on`,`usernameadmin`,`passwordadmin`,`barcode`,`email`,`separationdate`,`userrole`,`useraccess`,`safetycouncil`,`vacationleave`,`sickleave`,`emergencyleave`,`earnVL`,`earnSL`,`earnEL`,`civil_status`,`emergency_contact`,`emergency_number`,`sss_number`,`philhealth_number`,`pagibig_number`,`tin_number`,`work_status`,`cedula_govid`,`rate`) VALUES (389,'401','A.Domulot','$2y$10$LxgVHR4n/BXfqgqpuwYOoOPdksE8R5zb.KBFiFPrwl5zk2ouXHcbe','Arnold','Viray','Domulot','Blk 1 Lot 5 classic 2 Brgy San vicente Santo tomas Batangas','1989-08-24','09630008001','Male',8,7,2,4,'2025-11-27','Untitled design (5).png','2025-11-28','','','','domulot1026@gmail.com','0000-00-00','0',0,0,0,0,0,0,0,0,'','',0,0,0,0,0,'','',0.00);
INSERT INTO `` (`id`,`employee_no`,`username`,`password`,`firstname`,`middlename`,`lastname`,`address`,`birthdate`,`contact_info`,`gender`,`position_id`,`department_id`,`schedule_id`,`organization_id`,`datehired`,`photo`,`created_on`,`usernameadmin`,`passwordadmin`,`barcode`,`email`,`separationdate`,`userrole`,`useraccess`,`safetycouncil`,`vacationleave`,`sickleave`,`emergencyleave`,`earnVL`,`earnSL`,`earnEL`,`civil_status`,`emergency_contact`,`emergency_number`,`sss_number`,`philhealth_number`,`pagibig_number`,`tin_number`,`work_status`,`cedula_govid`,`rate`) VALUES (391,'399','mathewlds','','mathew','labog','delos santos','south ville 6 b-2 l-129 brgy kay-anlog calamba city, laguna','1997-12-20','09919160927','Male',35,7,2,0,'2025-11-19','','2025-12-01','','','','matkee28@gmail.com','2025-10-10','',0,0,0,0,0,0,0,0,'','',0,0,0,0,0,'','',0.00);
