

<script>
    $(document).ready(function () {
        let dcnModal = new bootstrap.Modal(document.getElementById('dcnModal'));
        let currentEntryId = null;

        document.getElementById('manualDcnMode').addEventListener('change', function (e) {
            const isManual = e.target.checked;

            if (isManual) {
                document.getElementById('autoGeneratedSection').style.display = 'none';
                document.getElementById('manualDcnSection').style.display = 'block';
                document.getElementById('formatBreakdown').style.display = 'none';

                document.getElementById('dcnSuffix').value = '';
                document.getElementById('dcnSuffix').disabled = true;

                document.getElementById('manualDcnInput').disabled = false;
                document.getElementById('manualDcnInput').focus();

                updateManualDcnPreview();
            } else {
                document.getElementById('autoGeneratedSection').style.display = 'block';
                document.getElementById('manualDcnSection').style.display = 'none';
                document.getElementById('formatBreakdown').style.display = 'block';

                document.getElementById('manualDcnInput').value = '';
                document.getElementById('manualDcnInput').disabled = true;

                document.getElementById('dcnSuffix').disabled = false;

                updateDcnPreview();
            }
        });

        document.getElementById('manualDcnInput').addEventListener('input', function () {
            updateManualDcnPreview();
        });

        function updateManualDcnPreview() {
            const manualDcn = document.getElementById('manualDcnInput').value.trim();

            if (manualDcn) {
                document.getElementById('dcnPreview').innerHTML = `<i class='bx bx-barcode'></i> ${manualDcn}`;
                document.getElementById('dcnStatus').innerHTML = '<div class="alert alert-info alert-sm mb-0"><i class="bx bx-info-circle"></i> Manual DCN mode - no format validation</div>';
                document.getElementById('saveDcnBtn').disabled = false;

                document.getElementById('manualDcnInput').classList.remove('is-invalid');
                document.getElementById('manualDcnInput').classList.add('is-valid');
                document.getElementById('manualDcnStatus').innerHTML = '<i class="bx bx-check-circle text-success"></i> DCN ready to save';
            } else {
                document.getElementById('dcnPreview').innerHTML = '<i class="bx bx-barcode"></i> Enter DCN number...';
                document.getElementById('dcnStatus').innerHTML = '';
                document.getElementById('saveDcnBtn').disabled = true;

                document.getElementById('manualDcnInput').classList.remove('is-invalid', 'is-valid');
                document.getElementById('manualDcnStatus').innerHTML = '<span class="text-muted">Enter any DCN format you need</span>';
            }
        }

        function updateDcnPreview() {
            const categorySelect = document.getElementById('modalCategory');
            const customerSelect = document.getElementById('modalCustomer');
            const suffixInput = document.getElementById('dcnSuffix');

            const categoryCode = categorySelect.options[categorySelect.selectedIndex]?.dataset.code;
            const customerCode = customerSelect.options[customerSelect.selectedIndex]?.dataset.code;
            const suffix = suffixInput.value;

            const isValidSuffix = /^\d{3}$/.test(suffix);

            if (categoryCode && customerCode && suffix) {
                if (isValidSuffix) {
                    const currentYear = new Date().getFullYear().toString().slice(-2);
                    const dcnPreview = `${categoryCode}${currentYear}-${customerCode}-${suffix}`;

                    document.getElementById('dcnPreview').innerHTML = `<i class='bx bx-barcode'></i> ${dcnPreview}`;
                    document.getElementById('dcnStatus').innerHTML = '<div class="alert alert-success alert-sm mb-0"><i class="bx bx-check-circle"></i> DCN ready to assign</div>';
                    document.getElementById('saveDcnBtn').disabled = false;

                    suffixInput.classList.remove('is-invalid');
                    suffixInput.classList.add('is-valid');
                    document.getElementById('suffixStatus').innerHTML = '<i class="bx bx-check-circle text-success"></i> Valid 3-digit suffix';
                } else {
                    document.getElementById('dcnPreview').innerHTML = '<i class="bx bx-error-circle"></i> Invalid suffix format';
                    document.getElementById('dcnStatus').innerHTML = '<div class="alert alert-warning alert-sm mb-0"><i class="bx bx-exclamation-triangle"></i> Suffix must be exactly 3 digits (e.g., 001, 025, 999)</div>';
                    document.getElementById('saveDcnBtn').disabled = true;

                    suffixInput.classList.add('is-invalid');
                    suffixInput.classList.remove('is-valid');
                    document.getElementById('suffixStatus').innerHTML = '<i class="bx bx-error-circle text-danger"></i> Suffix must be exactly 3 digits';
                }
            } else {
                document.getElementById('dcnPreview').innerHTML = '<i class="bx bx-barcode"></i> Waiting for complete data...';
                document.getElementById('dcnStatus').innerHTML = '';
                document.getElementById('saveDcnBtn').disabled = true;

                suffixInput.classList.remove('is-invalid', 'is-valid');
            }
        }

        document.getElementById('modalCategory').addEventListener('change', function () {
            const saveCategoryCustomerRow = document.getElementById('saveCategoryCustomerRow');
            if (saveCategoryCustomerRow && saveCategoryCustomerRow.style.display !== 'none') {
                updateDcnPreview();
            }
        });

        document.getElementById('modalCustomer').addEventListener('change', function () {
            const saveCategoryCustomerRow = document.getElementById('saveCategoryCustomerRow');
            if (saveCategoryCustomerRow && saveCategoryCustomerRow.style.display !== 'none') {
                updateDcnPreview();
            }
        });

        const saveCategoryCustomerBtn = document.getElementById('saveCategoryCustomerBtn');
        if (saveCategoryCustomerBtn) {
            saveCategoryCustomerBtn.addEventListener('click', function () {
                const entryId = currentEntryId;
                const categoryId = document.getElementById('modalCategory').value;
                const customerId = document.getElementById('modalCustomer').value;

                if (!categoryId || !customerId) {
                    $('#categoryCustomerSuccessRow').hide();
                    $('#categoryCustomerWarningRow').remove();
                    $('#categoryCustomerErrorRow').remove();
                    const warningHtml = `
                        <div class="row" id="categoryCustomerWarningRow">
                            <div class="col-12">
                                <div class="alert alert-warning mb-3" role="alert">
                                    <i class='bx bx-error-circle'></i>
                                    <strong>Incomplete!</strong> Please select both category and customer before saving.
                                </div>
                            </div>
                        </div>
                    `;
                    $('#saveCategoryCustomerRow').after(warningHtml);

                    setTimeout(() => {
                        $('#categoryCustomerWarningRow').fadeOut(300, function () {
                            $(this).remove();
                        });
                    }, 3000);
                    return;
                }

                $('#categoryCustomerWarningRow').remove();
                $('#categoryCustomerErrorRow').remove();

                const saveBtn = document.getElementById('saveCategoryCustomerBtn');
                const originalBtnHtml = saveBtn.innerHTML;
                saveBtn.disabled = true;
                saveBtn.innerHTML = '<span class="spinner-border spinner-border-sm me-2"></span>Saving...';

                $.ajax({
                    url: `/document-registry/${entryId}`,
                    method: 'PUT',
                    data: {
                        category_id: categoryId,
                        customer_id: customerId,
                        _token: $('meta[name="csrf-token"]').attr('content')
                    },
                    success: function (response) {
                        if (response.success) {
                            $('#saveCategoryCustomerRow').hide();
                            $('#categoryCustomerSuccessRow').show();

                            if (response.entry.category) {
                                $('#modalCategory').val(response.entry.category_id).prop('disabled', true);
                                $('#categoryStatus').html('<i class="bx bx-check-circle text-success"></i> ' +
                                    response.entry.category.name + ' (' + response.entry.category.code + ')');
                            }

                            if (response.entry.customer) {
                                $('#modalCustomer').val(response.entry.customer_id).prop('disabled', true);
                                $('#customerStatus').html('<i class="bx bx-check-circle text-success"></i> ' +
                                    response.entry.customer.name + ' (' + response.entry.customer.code + ')');
                            }

                            $('#dcnStatus').html('');
                            $('#suffixStatus').html('<i class="bx bx-info-circle text-info"></i> Enter a unique 3-digit number (001-999)');
                            document.getElementById('dcnSuffix').disabled = false;

                            $.ajax({
                                url: `/dcn/${entryId}/data`,
                                method: 'GET',
                                success: function (dataResponse) {
                                    if (dataResponse.success && dataResponse.entry) {
                                        if (dataResponse.entry.suggested_suffix) {
                                            $('#dcnSuffix').val(dataResponse.entry.suggested_suffix);
                                            $('#suffixStatus').html('<i class="bx bx-lightbulb text-warning"></i> Suggested next available suffix: ' + dataResponse.entry.suggested_suffix);
                                        }

                                        updateDcnPreview();
                                        document.getElementById('dcnSuffix').focus();
                                    }
                                },
                                error: function () {
                                    updateDcnPreview();
                                    document.getElementById('dcnSuffix').focus();
                                }
                            });

                            document.getElementById('saveDcnBtn').disabled = false;

                            setTimeout(function () {
                                $('#categoryCustomerSuccessRow').fadeOut(300);
                            }, 5000);
                        }
                    },
                    error: function (xhr) {
                        saveBtn.disabled = false;
                        saveBtn.innerHTML = originalBtnHtml;

                        const response = xhr.responseJSON;
                        let errorMessage = 'An error occurred while saving changes.';
                        if (response && response.message) {
                            errorMessage = response.message;
                        } else if (response && response.errors) {
                            errorMessage = Object.values(response.errors).flat().join('<br>');
                        }

                        $('#categoryCustomerSuccessRow').hide();
                        $('#categoryCustomerErrorRow').remove();
                        const errorHtml = `
                            <div class="row" id="categoryCustomerErrorRow">
                                <div class="col-12">
                                    <div class="alert alert-danger mb-3" role="alert">
                                        <i class='bx bx-error-circle'></i>
                                        <strong>Error!</strong> ${errorMessage}
                                    </div>
                                </div>
                            </div>
                        `;
                        $('#saveCategoryCustomerRow').after(errorHtml);

                        setTimeout(() => {
                            $('#categoryCustomerErrorRow').fadeOut(300, function () {
                                $(this).remove();
                            });
                        }, 5000);
                    }
                });
            });
        }

        document.getElementById('dcnSuffix').addEventListener('input', function (e) {
            const suffix = e.target.value.trim();

            const autoCompletionDiv = document.getElementById('suffixAutoCompletion');
            const suffixValueDiv = document.getElementById('suffixAutoCompletionValue');

            if (suffix.length === 3) {
                autoCompletionDiv.style.display = 'block';

                const categoryCode = document.getElementById('modalCategory').selectedOptions[0]?.dataset.code || '';
                const customerCode = document.getElementById('modalCustomer').selectedOptions[0]?.dataset.code || '';

                const currentYear = new Date().getFullYear().toString().slice(-2);
                const autoCompleteDcn = `${categoryCode}${currentYear}-${customerCode}-${suffix}`;
                suffixValueDiv.innerText = autoCompleteDcn;

                document.getElementById('dcnPreview').innerHTML = `<i class='bx bx-barcode'></i> ${autoCompleteDcn}`;
                document.getElementById('dcnStatus').innerHTML = '<div class="alert alert-success alert-sm mb-0"><i class="bx bx-check-circle"></i> DCN ready to assign</div>';
                document.getElementById('saveDcnBtn').disabled = false;
            } else {
                autoCompletionDiv.style.display = 'none';

                document.getElementById('dcnPreview').innerHTML = '<i class="bx bx-barcode"></i> Select category, customer, and suffix to preview DCN';
                document.getElementById('dcnStatus').innerHTML = '';
                document.getElementById('saveDcnBtn').disabled = true;
            }
        });

        function loadEntryData(entryId) {
            $.ajax({
                url: `/dcn/${entryId}/data`,
                method: 'GET',
                success: function (response) {
                    if (response.success && response.entry) {
                        const entry = response.entry;

                        $('#modalOriginator').val(entry.originator_name || '-');

                        if (entry.submitted_at) {
                            const submittedDate = new Date(entry.submitted_at);
                            const formattedSubmitted = submittedDate.toLocaleDateString('en-US', {
                                month: '2-digit',
                                day: '2-digit',
                                year: 'numeric'
                            }) + ' ' + submittedDate.toLocaleTimeString('en-US', {
                                hour: '2-digit',
                                minute: '2-digit',
                                hour12: true
                            });
                            $('#modalRegistrationDate').val(formattedSubmitted);
                        } else {
                            $('#modalRegistrationDate').val('-');
                        }

                        if (entry.implemented_at) {
                            const implementedDate = new Date(entry.implemented_at);
                            const formattedImplemented = implementedDate.toLocaleDateString('en-US', {
                                month: '2-digit',
                                day: '2-digit',
                                year: 'numeric'
                            }) + ' ' + implementedDate.toLocaleTimeString('en-US', {
                                hour: '2-digit',
                                minute: '2-digit',
                                hour12: true
                            });
                            $('#modalEffectiveDate').val(formattedImplemented);
                        } else {
                            $('#modalEffectiveDate').val('-');
                        }

                        $('#modalDocumentNo').val(entry.document_no || '-');
                        $('#modalRevisionNo').val(entry.revision_no || '-');
                        $('#modalDeviceName').val(entry.device_name || '-');
                        $('#modalTitle').val(entry.document_title || '-');

                        if (entry.customer_id && entry.category_id && entry.customer && entry.category) {
                            $('#modalCustomer').val(entry.customer_id).prop('disabled', true);
                            $('#customerStatus').html('<i class="bx bx-check-circle text-success"></i> ' + entry.customer.name + ' (' + entry.customer.code + ')');

                            $('#modalCategory').val(entry.category_id).prop('disabled', true);
                            $('#categoryStatus').html('<i class="bx bx-check-circle text-success"></i> ' + entry.category.name + ' (' + entry.category.code + ')');

                            $('#saveCategoryCustomerRow').hide();
                            $('#categoryCustomerSuccessRow').hide();

                            if (entry.suggested_suffix) {
                                $('#dcnSuffix').val(entry.suggested_suffix);
                                $('#suffixStatus').html('<i class="bx bx-lightbulb text-warning"></i> Suggested next available suffix: ' + entry.suggested_suffix);
                            }

                            if (entry.current_dcn) {
                                const suffixMatch = entry.current_dcn.match(/-(\d{3})$/);
                                if (suffixMatch) {
                                    $('#dcnSuffix').val(suffixMatch[1]);
                                } else {
                                    document.getElementById('manualDcnMode').checked = true;
                                    document.getElementById('autoGeneratedSection').style.display = 'none';
                                    document.getElementById('manualDcnSection').style.display = 'block';
                                    document.getElementById('formatBreakdown').style.display = 'none';
                                    document.getElementById('dcnSuffix').disabled = true;
                                    document.getElementById('manualDcnInput').disabled = false;
                                    document.getElementById('manualDcnInput').value = entry.current_dcn;
                                }

                                const currentDcnHtml = `
                                    <div class="alert alert-info alert-sm mb-2">
                                        <i class="bx bx-info-circle"></i>
                                        <strong>Current DCN:</strong> ${entry.current_dcn}
                                    </div>
                                `;
                                document.getElementById('dcnStatus').innerHTML = currentDcnHtml;
                            }

                            document.getElementById('saveDcnBtn').disabled = false;

                            updateDcnPreview();
                        } else {
                            let missingFields = [];

                            if (!entry.customer_id || !entry.customer) {
                                $('#modalCustomer').prop('disabled', false);
                                $('#customerStatus').html('<i class="bx bx-exclamation-triangle text-warning"></i> No customer assigned - select one below');
                                missingFields.push('Customer');
                            } else {
                                $('#modalCustomer').val(entry.customer_id).prop('disabled', false);
                                $('#customerStatus').html('<i class="bx bx-info-circle text-info"></i> ' + entry.customer.name + ' (' + entry.customer.code + ') - can be changed');
                            }

                            if (!entry.category_id || !entry.category) {
                                $('#modalCategory').prop('disabled', false);
                                $('#categoryStatus').html('<i class="bx bx-exclamation-triangle text-warning"></i> No category assigned - select one below');
                                missingFields.push('Category');
                            } else {
                                $('#modalCategory').val(entry.category_id).prop('disabled', false);
                                $('#categoryStatus').html('<i class="bx bx-info-circle text-info"></i> ' + entry.category.name + ' (' + entry.category.code + ') - can be changed');
                            }

                            $('#saveCategoryCustomerRow').show();
                            $('#categoryCustomerSuccessRow').hide();

                            $('#suffixStatus').html('<i class="bx bx-info-circle text-info"></i> Select category & customer, then save changes before assigning DCN');

                            document.getElementById('dcnPreview').innerHTML = '<i class="bx bx-info-circle"></i> Select and save Category & Customer first';
                            document.getElementById('dcnStatus').innerHTML = `
                                <div class="alert alert-warning alert-sm mb-0">
                                    <i class="bx bx-exclamation-triangle"></i>
                                    ${missingFields.join(' and ')} not assigned.
                                    <strong>Select values above and click "Save Category & Customer Changes"</strong> before assigning DCN.
                                </div>
                            `;

                            document.getElementById('saveDcnBtn').disabled = true;
                        }
                    } else {
                        document.getElementById('dcnPreview').innerHTML = '<i class="bx bx-error-circle"></i> Error loading entry data';
                        $('#customerStatus').html('<i class="bx bx-error-circle text-danger"></i> Error loading data');
                        $('#categoryStatus').html('<i class="bx bx-error-circle text-danger"></i> Error loading data');
                        $('#suffixStatus').html('<i class="bx bx-error-circle text-danger"></i> Error loading data');
                    }
                },
                error: function (xhr) {
                    console.error('Error loading entry data:', xhr);
                    document.getElementById('dcnPreview').innerHTML = '<i class="bx bx-error-circle"></i> Error loading entry data';
                    $('#customerStatus').html('<i class="bx bx-error-circle text-danger"></i> Error loading data');
                    $('#categoryStatus').html('<i class="bx bx-error-circle text-danger"></i> Error loading data');
                    $('#suffixStatus').html('<i class="bx bx-error-circle text-danger"></i> Error loading data');
                }
            });
        }

        document.getElementById('saveDcnBtn').addEventListener('click', function () {
            const isManualMode = document.getElementById('manualDcnMode').checked;

            let dcnNumber;
            let formData = new FormData();
            formData.append('entry_id', currentEntryId);

            if (isManualMode) {
                dcnNumber = document.getElementById('manualDcnInput').value.trim();

                if (!dcnNumber) {
                    Swal.fire({
                        title: 'Missing DCN!',
                        text: 'Please enter a DCN number.',
                        icon: 'warning',
                        confirmButtonText: 'OK'
                    });
                    return;
                }

                formData.append('manual_dcn', dcnNumber);
                formData.append('is_manual', '1');
            } else {
                const customerId = document.getElementById('modalCustomer').value;
                const categoryId = document.getElementById('modalCategory').value;
                const suffix = document.getElementById('dcnSuffix').value;

                if (!customerId || !categoryId || !suffix) {
                    Swal.fire({
                        title: 'Incomplete Data!',
                        text: 'Customer, category, and suffix are required. Please ensure the document registry entry has complete information.',
                        icon: 'warning',
                        confirmButtonText: 'OK'
                    });
                    return;
                }

                formData.append('customer_id', customerId);
                formData.append('category_id', categoryId);
                formData.append('dcn_suffix', suffix);
                formData.append('is_manual', '0');
            }

            const entryId = currentEntryId;

            Swal.fire({
                title: 'Processing...',
                text: 'Saving DCN number',
                allowOutsideClick: false,
                showConfirmButton: false,
                willOpen: () => {
                    Swal.showLoading();
                }
            });

            $.ajax({
                url: `/dcn/${entryId}/update-dcn`,
                method: 'POST',
                data: formData,
                processData: false,
                contentType: false,
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                success: function (response) {
                    if (response.success) {
                        dcnModal.hide();

                        Swal.fire({
                            title: 'Success!',
                            html: `DCN number saved successfully!<br><strong>${response.dcn_number}</strong>`,
                            icon: 'success',
                            confirmButtonText: 'OK'
                        }).then(() => {
                            location.reload();
                        });
                    }
                },
                error: function (xhr) {
                    const response = xhr.responseJSON;
                    let errorMessage = 'An error occurred while saving the DCN number.';

                    if (response && response.errors) {
                        errorMessage = Object.values(response.errors).flat().join('<br>');
                    } else if (response && response.message) {
                        errorMessage = response.message;
                    }

                    Swal.fire({
                        title: 'Error!',
                        html: errorMessage,
                        icon: 'error',
                        confirmButtonText: 'OK'
                    });
                }
            });
        });

        window.openDcnModal = function (entryId) {
            currentEntryId = entryId;
            document.getElementById('entryId').value = entryId;

            document.getElementById('dcnForm').reset();
            document.getElementById('dcnPreview').innerHTML = '<i class="bx bx-barcode"></i> Loading entry data...';
            document.getElementById('dcnStatus').innerHTML = '';
            document.getElementById('saveDcnBtn').disabled = true;

            $('#saveCategoryCustomerRow').hide();
            $('#categoryCustomerSuccessRow').hide();
            $('#categoryCustomerWarningRow').remove();
            $('#categoryCustomerErrorRow').remove();

            document.getElementById('manualDcnMode').checked = false;
            document.getElementById('autoGeneratedSection').style.display = 'block';
            document.getElementById('manualDcnSection').style.display = 'none';
            document.getElementById('formatBreakdown').style.display = 'block';
            document.getElementById('dcnSuffix').disabled = false;
            document.getElementById('manualDcnInput').disabled = true;

            document.getElementById('dcnSuffix').classList.remove('is-invalid', 'is-valid');
            document.getElementById('manualDcnInput').classList.remove('is-invalid', 'is-valid');

            document.getElementById('customerStatus').innerHTML = 'Loading...';
            document.getElementById('categoryStatus').innerHTML = 'Loading...';
            document.getElementById('suffixStatus').innerHTML = 'Enter a unique 3-digit number (001-999)';
            document.getElementById('manualDcnStatus').innerHTML = '<span class="text-muted">Enter any DCN format you need</span>';

            loadEntryData(entryId);

            dcnModal.show();
        };

        window.clearDcn = function (entryId) {
            Swal.fire({
                title: 'Clear DCN Number?',
                text: 'Are you sure you want to clear the DCN number for this entry?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: '<i class="bx bx-check"></i> Yes, clear it!',
                cancelButtonText: '<i class="bx bx-x"></i> Cancel'
            }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire({
                        title: 'Processing...',
                        text: 'Clearing DCN number',
                        allowOutsideClick: false,
                        showConfirmButton: false,
                        willOpen: () => {
                            Swal.showLoading();
                        }
                    });

                    $.ajax({
                        url: `/dcn/${entryId}/clear-dcn`,
                        method: 'POST',
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        },
                        success: function (response) {
                            if (response.success) {
                                Swal.fire({
                                    title: 'Cleared!',
                                    text: 'DCN number has been cleared successfully.',
                                    icon: 'success',
                                    confirmButtonText: 'OK'
                                }).then(() => {
                                    location.reload();
                                });
                            }
                        },
                        error: function () {
                            Swal.fire({
                                title: 'Error!',
                                text: 'An error occurred while clearing the DCN number.',
                                icon: 'error',
                                confirmButtonText: 'OK'
                            });
                        }
                    });
                }
            });
        };

        window.showDcnFormatInfo = function () {
            Swal.fire({
                title: '<i class="bx bx-info-circle"></i> DCN Format Information',
                html: `
                    <div class="text-start">
                        <h6>DCN Format Structure:</h6>
                        <div class="bg-light p-3 rounded mb-3">
                            <strong>Format:</strong> [CategoryCode][Year]-[CustomerCode]-[3DigitSuffix]
                        </div>

                        <h6>Example:</h6>
                        <div class="bg-info bg-opacity-10 p-3 rounded mb-3">
                            <strong>CNA25-ALL-001</strong>
                            <ul class="mt-2 mb-0 text-start">
                                <li><strong>CNA</strong> = Category Code</li>
                                <li><strong>25</strong> = Current Year (2025)</li>
                                <li><strong>ALL</strong> = Customer Code</li>
                                <li><strong>001</strong> = User-defined 3-digit suffix</li>
                            </ul>
                        </div>

                        <h6>Notes:</h6>
                        <ul class="text-start">
                            <li>Year is automatically generated based on current year (2-digit format)</li>
                            <li>Category and Customer codes are taken from their respective master data</li>
                            <li>The 3-digit suffix must be unique for each DCN combination</li>
                            <li>System will check for duplicate DCN numbers before saving</li>
                        </ul>
                    </div>
                `,
                width: '600px',
                confirmButtonText: '<i class="bx bx-check"></i> Got it!',
                customClass: {
                    popup: 'text-start'
                }
            });
        };
    });
</script>
